### ISSUE TITLE
Adding new points in intuitive manner

### ISSUE THREAD

**Issue by skynet** [influxdb/influxdb-php#10]
Seems more intuitive to me how https://github.com/corley/influxdb-php-sdk is adding new points:

```
$client->mark([
    "tags" => [
        "dc" => "eu-west-1",
    ],
    "points" => [
        [
            "measurement" => "instance",
            "fields" => [
                "cpu" => 18.12,
                "free" => 712423,
            ],
        ],
    ]
]);
```

Compared to what we have in the README example here:

```
    $points = array(
        new Point(
            'test_metric',
            0.64,
            array('host' => 'server01', 'region' => 'us-west'),
            array('cpucount' => 10),
            1435255849
        )
    );

    $newPoints = $database->writePoints($points, Database::PRECISION_SECONDS);
```
Can we do the same on this repo? It is relatively hard for someone to understand InfluxDB from your example while example at the top makes it much easier. I, myself, don't even know how to rewrite example at the to work with this library.

**Comment by danibrutal** [comment]
Hey Skynet,

I don't totally agree is more intuitive using arrays than using objects. It seems to me more readable "insert Points[]" than "insert [['fields]....".
In the other hand, maybe we could create an **PointsBuilder** to create Points in a more abstract way.
By default, we use the inline writing by default in a transparent way, not like in the https://github.com/corley/influxdb-php-sdk:
```php
$udp = new UdpAdapter($options);
$udp->write("cpu,region=us-west,host=serverA,env=prod,target=servers,zone=1c cpu=18.12,free=712432 1257894000");
```

So Objects in this case can provide an abstraction that later can give us more flexibility.

**Comment by thecodeassassin** [comment]
@skynet i really believe the way we do it is more intuitive and more in line with the python library. Doing it using the Point object offers us a way to regulate the parameters of a metric thus making it more verbose and readable.

**Comment by skynet** [comment]
I still don't see the reason to insert a single measurement value. In example at the top it inserts two. In most cases we do insert multiple values:
```
            "measurement" => "instance",
            "fields" => [
                "cpu" => 18.12,
                "free" => 712423,
            ],
```

**Comment by thecodeassassin** [comment]
@skynet this will be possible in 1.0.0:

```php

$points = [
    new Point(
        'instance', // the name of the measurement
        null, // measurement value
        ['host' => 'server01', 'region' => 'us-west'],
        ['cpucount' => 10, 'free' => 1],
        exec('date +%s%N')
    ),
    new Point(
        'instance', // the name of the measurement
        null, // measurement value
        ['host' => 'server01', 'region' => 'us-west'],
        ['cpucount' => 10, 'free' => 2],
        exec('date +%s%N')
    )
];

$result = $database->writePoints($points);
```

**Comment by skynet** [comment]
It probably makes sense now. Is this due to some sort of InfluxDB limitation or just the way that you built the library?

**Comment by thecodeassassin** [comment]
@skynet well previously we required the value to be there because we didn't consider people using the fields like this. I would actually not do it like this and add all measurements separately. But we want to support as many use cases as possible. 

But it was designed with the main use-case in mind, so that's why it was built like that.

**Comment by skynet** [comment]
Is there any impact on InfluxDB performance when we do it like in my example? How soon are we going to have 1.0.0 available? Can you also include benchmark tests? Thank you.

Looks like UDP is 200 times faster at inserts:
```
    Method Name                Iterations    Average Time      Ops/second
    ------------------------  ------------  --------------    -------------
    sendDataUsingHttpAdapter: [1,000     ] [0.0167509446144] [59.69813]
    sendDataUsingUdpAdapter : [1,000     ] [0.0000905156136] [11,047.81773]
```

**Comment by skynet** [comment]
Can you also include benchmark tests? Thank you.

Looks like UDP is 200 times faster at inserts:
```
    Method Name                Iterations    Average Time      Ops/second
    ------------------------  ------------  --------------    -------------
    sendDataUsingHttpAdapter: [1,000     ] [0.0167509446144] [59.69813]
    sendDataUsingUdpAdapter : [1,000     ] [0.0000905156136] [11,047.81773]

**Comment by thecodeassassin** [comment]
There are no plans to write benchmarked tests at the moment.

**Comment by skynet** [comment]
No problem.

**Comment by danibrutal** [comment]
@skynet that's fast :). Maybe you can share your benchmarks ?

**Comment by skynet** [comment]
I will, as soon as I run some :)

**Comment by danibrutal** [comment]
@skynet cool :+1:

**Comment by danibrutal** [comment]
@skynet Are you using InfluxDB (v0.9.1) in a production environment ? Did you find any issue ?

**Comment by skynet** [comment]
Yes, in production and all seems good with InfluxDB 0.9.1. But I don't have tough requirements - I use it only for monitoring jobs and not for storing critical data that other systems rely upon. Running some 20K jobs/day, sending processing results from within php to InfluxDB and displaying them with Grafana. Works like a charm!
