### ISSUE TITLE
this is why???

### ISSUE THREAD

**Issue by zengzhihai110** [influxdb/influxdb-php#14]
include('influxdb-php-sdk1/autoload.php');

/*
$host = '127.0.0.1';
$port = 8086;
$dbname = 'ddd';
$client = new InfluxDB\Client($host, $port);

fetch the database
$database = $client->selectDB('ddd');

// executing a query will yield a resultset object
$result = $database->query('select * from log LIMIT 5');

var_dump($result);
 */

// directly get the database object
$database = InfluxDB\Client::fromDSN(sprintf('influxdb://user:pass@%s:%s/%s', '127.0.0.1', 8086, 'test_db'));

    // get the client to retrieve other databases
$client = $database->getClient();   

// set the UDP driver in the client
$client->setDriver(new \InfluxDB\Driver\UDP($client->getHost(), 4444));

$points = [
    new Point(
        'test_metric',
        0.84,
        ['host' => 'server01', 'region' => 'us-west'],
        ['cpucount' => 10],
        exec('date +%s%N') // this will produce a nanosecond timestamp in Linux operating systems
    )
];

// now just write your points like you normally would
$result = $database->writePoints($points);

results:

Fatal error: Class 'Point' not found in /mnt/hgfs/windows-webserver/study/influxdb/t4.php on line 47

**Comment by danibrutal** [comment]
Hi @zengzhihai110, 
Since you are not using any namespace nor use stament, I guess you should provide the whole namespace for the Point class, as you are doing for the rest of classes.
