### ISSUE TITLE
Active development

### ISSUE THREAD

**Issue by thecodeassassin** [influxdb/influxdb-php#2]
Dear influxDB,

My team and at leaseweb i are creating a library for php that is based on the python library and should work the same way. Do you want us to create the library independently or can we have push rights to this repo?

Our repo (work in progress): https://github.com/LeaseWeb/influxdb-php

**Comment by skynet** [comment]
:+1: I have tested the library by @thecodeassassin and it works.

**Comment by thecodeassassin** [comment]
@beckettsean if you want we can continue the development of our client in this repository

**Comment by beckettsean** [comment]
@thecodeassassin I haven't been monitoring issues outside influxdb/influxdb and influxdb/influxdb.com so I didn't see this until now, thanks for the @ mention! Let me ask the founders what they prefer.

@toddboom @pauldix should we keep the PHP library in our GitHub account? If so, any objection to giving commit rights to this repo to @thecodeassassin?

**Comment by pauldix** [comment]
@beckettsean would be nice to keep the library in our account. We can grant contributor rights to @thecodeassassin if you're willing to be the maintainer?

**Comment by thecodeassassin** [comment]
@danibrutal and i are maintaining the leaseweb/influxdb-php library. We would very much like to be maintainers of this library. We can merge all our work into this repository if you will grant us the appropriate rights.

**Comment by beckettsean** [comment]
Team `php-team` created with @danibrutal and @thecodeassassin as members with full write permissions. @pauldix @toddboom
