### ISSUE TITLE
authentication failed while calling Database::writePoints()

### ISSUE THREAD

**Issue by riverlet** [influxdb/influxdb-php#21]
In src/InfluxDB/Database.php:

    if (!empty($this->username) && !empty($this->password)) {
            $parameters += ['auth' => [$this->username, $this->password]];
    }

it checks username and password, but the two value is read from the Database class, but it seems that two values are defined in the Client class. so i'm always get a false result.

is this a bug ?

**Comment by thecodeassassin** [comment]
Hi @riverlet, we have determined this to be a bug. It will be resolved a.s.a.p. Thank you for mentioning it. +1

**Comment by danibrutal** [comment]
@riverlet thanks for spotting the bug. I created a PR to fix it here https://github.com/influxdb/influxdb-php/pull/22

**Comment by riverlet** [comment]
Thank you very much for the prompt reply.
