### ISSUE TITLE
Data is NOT getting written to DB - HTTP 400/ bad timestamp?

### ISSUE THREAD

**Issue by andig** [influxdb/influxdb-php#24]
I have a simple client that should write/read data- yet the result is always empty, be it Admin interface or client. The code is entirely from the readme:

	$client = new InfluxDB\Client('127.0.0.1', 8086);

	// fetch the database
	$database = $client->selectDB('test');

	// executing a query will yield a resultset object
	$result = $database->query('select * from test_metric LIMIT 5');

	// get the points from the resultset yields an array
	$points = $result->getPoints();
	print_r($points);

	// create an array of points
	$points = array(
	    new Point(
	        'test_metric', // name of the measurement
	        0.64, // the measurement value
	        ['host' => 'server01', 'region' => 'us-west'], // optional tags
	        ['cpucount' => 10], // optional additional fields
	        1435255849 // Time precision has to be set to seconds!
	    ),
	    new Point(
	        'test_metric', // name of the measurement
	        0.84, // the measurement value
	        ['host' => 'server01', 'region' => 'us-west'], // optional tags
	        ['cpucount' => 10], // optional additional fields
	        1435255849 // Time precision has to be set to seconds!
	    )
	);

	// we are writing unix timestamps, which have a second precision
	$result = $database->writePoints($points, Database::PRECISION_SECONDS);
	print_r($result);

	// executing a query will yield a resultset object
	$result = $database->query('SHOW MEASUREMENTS')->getPoints();
	print_r($result);

This happens against Windows server, current download.

**Comment by andig** [comment]
**Update:** in the server console I can see the following happening:

	[query] 2015/10/15 09:42:57 SELECT * FROM "test"."default".test_metric LIMIT 5
	[http] 2015/10/15 09:42:57 127.0.0.1 - - [15/Oct/2015:09:42:57 +0200] GET /query?q=select+%2A+from+test_metric+LIMIT+5&db=test HTTP/1.1 200 16 - GuzzleHttp/6.1.0 curl/7.40.0 PHP/5.6.7 5a6f0831-7310-11e5-8026-000000000000 0
	[http] 2015/10/15 09:42:57 127.0.0.1 - - [15/Oct/2015:09:42:57 +0200] POST /write?db=test HTTP/1.1 400 110 - GuzzleHttp/6.1.0 curl/7.40.0 PHP/5.6.7 5a73ea71-7310-11e5-8027-000000000000 0
	[query] 2015/10/15 09:42:57 SHOW MEASUREMENTS
	[http] 2015/10/15 09:42:57 127.0.0.1 - - [15/Oct/2015:09:42:57 +0200] GET /query?q=SHOW+MEASUREMENTS&db=test HTTP/1.1 200 110 - GuzzleHttp/6.1.0 curl/7.40.0 PHP/5.6.7 5a757125-7310-11e5-8028-000000000000 2.0004ms

It seems the `POST` writing the data returns HTTP 400, yet no error is raised by the library. POST body looks ok from debuggging.

**Comment by mermetbt** [comment]
I had the same errors, and I agree about the fact it should be helpful to have an error message in case of the isSuccessful() == false. In every check, the default behavior is throwing an exception, but in this case there is only the return value.. without more informations.

**Comment by andig** [comment]
Unfortunately even the obvious fixes contributed don't get attention :(

**Comment by thecodeassassin** [comment]
@andig Sorry for the late reply. Please tag either me or @danibrutal  so we get notified sooner :)

Thanks for the PR!

**Comment by andig** [comment]
Excellent, thank you!
