### ISSUE TITLE
Support Symfony 3.0

### ISSUE THREAD

**Issue by sc0rp10** [influxdb/influxdb-php#31]
Symfony 3.0 will be released in the shortly (roadmap says `November, 2015`), but influxdb/influxdb-php requires `symfony/event-dispatcher: 2.*` that conflicted with symfony 3.0.
Do you can update dependency version to 2.*|3.*?

**Comment by sc0rp10** [comment]
I've made PR https://github.com/influxdb/influxdb-php/pull/32

**Comment by sc0rp10** [comment]
hey, @danibrutal! can you please tag new version with 3.0 support?

**Comment by sc0rp10** [comment]
@thecodeassassin ping

**Comment by thecodeassassin** [comment]
@sc0rp10 done :+1: thanks for your PR

Sorry for the late response; i was on vacation in Thailand.
